name: Publish JSR

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2

      - name: Publish Fresh
        run: deno publish

      - name: Publish @unabbreviated-fresh/init
        working-directory: ./init
        run: deno publish

      - name: Publish @unabbreviated-fresh/plugin-tailwindcss
        working-directory: ./plugin-tailwindcss
        run: deno publish

      - name: Publish @unabbreviated-fresh/update
        working-directory: ./update
        run: deno publish

      - name: Publish @unabbreviated-fresh/examples
        working-directory: ./examples
        run: deno publish
